Bring back defaultFeeReserve to network config to fix build errors
src/config/networks.ts:12:3 - error TS2741: Property 'defaultFeeReserve' is missing in type '{ name: "creditcoin"; endpoints: { lightClient: null; defaultRpcEndpoint: string; rpcEndpoints: { Gluwa: string; }; }; namespace: string; api: { unit: string; priceTicker: string; }; params: { auctionAdjust: number; ... 4 more ...; stakeTarget: number; }; ... 5 more ...; subscanEndpoint: string; }' but required in type 'Network'.

12   creditcoin: {
     ~~~~~~~~~~