Bring back TokenSVG as part of network configuration to fix build errors
src/config/networks.ts:31:5 - error TS2741: Property 'token' is missing in type '{ icon: FunctionComponent<SVGProps<SVGSVGElement> & { title?: string | undefined; }>; logo: { svg: FunctionComponent<SVGProps<SVGSVGElement> & { title?: string | undefined; }>; width: string; }; inline: { ...; }; }' but required in type '{ icon: FunctionComponent<SVGProps<SVGSVGElement> & { title?: string | undefined; }>; token: FunctionComponent<SVGProps<SVGSVGElement> & { ...; }>; logo: { ...; }; inline: { ...; }; }'.

31     brand: {
       ~~~~~